#!/bin/sh
#
# Usage: iterm-setup
# Description: copies settings from repo into iterm2
#


iterm_setup() {
    # symlink .dotfiles/iterm .itermcnf to ~
    #ln -s $HOME/.dotfiles/iterm/.itermcnf $HOME/.itermcnf && success "symlink for $HOME/.itermcnf folder created"

    # Specify the preferences directory
    defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
      if [[ $? -eq 0 ]]
      then
          success "successfully configured iTerm2 to use my settings!"
      else
          fail "failed to apply my settings." >&2
      fi
}

