{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "token.yaml.serviceAccountName" . }}
  labels:
{{ include "token.yaml.labels" . | nindent 4 }}
{{- end -}}
