#!/bin/sh
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.


# Install Homebrew
sh $DOTFILES/homebrew/install.sh 2>&1

# Install ZSH
sh $DOTFILES/zsh/install.sh 2>&1

# Install software
echo "› $DOTFILES/script/install"
$DOTFILES/script/install


