#!/bin/sh
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.

set -e

parentDirectory="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
dotfilesDirectory="$(cd "$( dirname "$parentDirectory" )" && pwd -P)"

displayUsageAndExit() {
	echo "dot -- dotfiles management"
	echo ""
	echo "Usage: dot [options]"
	echo ""
	echo "Options:"
	echo "  -e, --edit    Open dotfiles directory for editing"
	echo "  -h, --help    Show this help message and exit"
	exit
}

# Set macOS defaults
sh $DOTFILES/macos/set-defaults.sh

# Install Homebrew
sh $DOTFILES/homebrew/install.sh 2>&1

# Install ZSH
sh $DOTFILES/zsh/install.sh 2>&1

# Install software
echo "› $DOTFILES/script/install"
$DOTFILES/script/install